# Solutions of Explorations

#### Code from previous file

# _________________________________________________________________

In [2]:
import torch
import sklearn
from sklearn.datasets import load_iris
import numpy as np


print(f"Pytorch version : { torch.__version__ }")
print(f"sklearn - version : {sklearn.__version__}")



################################################
# Load the dataset

iris = load_iris()
X = iris.data
y = iris.target

print(f"X.datatype : {X.dtype}, y.datatype : {y.dtype}")


############################################
# Convertour dataset to pytorch tensors




# X is our feature matrix
# Neural networks typically expect input data to be float

X_tensor = torch.tensor(X, dtype=torch.float64)

# y is our label vector
# Labels for classification are often long integers
# Hence, the dtype 'long'
y_tensor = torch.tensor(y, dtype=torch.long)


# Let's see what we've created.
print("--- Tensor Properties ---")
print(f"Shape of features tensor: {X_tensor.shape}")
print(f"Shape of labels tensor: {y_tensor.shape}\n")

print(f"Data type of features tensor: {X_tensor.dtype}")
print(f"Data type of labels tensor: {y_tensor.dtype}\n")

# .device tells us if the tensor is on the CPU or a GPU. For now, it's CPU.
print(f"Device tensor is stored on: {X_tensor.device}\n")





# --- 4. See the Data ---
# Let's look at the first 5 rows of our data, now as a PyTorch Tensor.
print("--- First 5 Samples ---")
print("Features (X):")
print(X_tensor[:5])
print("\nLabels (y):")
print(y_tensor[:5])
print(f"Which correspond to flower types: {[iris.target_names[i] for i in y_tensor[:5]]}")


Pytorch version : 2.5.1
sklearn - version : 1.6.1
X.datatype : float64, y.datatype : int32
--- Tensor Properties ---
Shape of features tensor: torch.Size([150, 4])
Shape of labels tensor: torch.Size([150])

Data type of features tensor: torch.float64
Data type of labels tensor: torch.int64

Device tensor is stored on: cpu

--- First 5 Samples ---
Features (X):
tensor([[5.1000, 3.5000, 1.4000, 0.2000],
        [4.9000, 3.0000, 1.4000, 0.2000],
        [4.7000, 3.2000, 1.3000, 0.2000],
        [4.6000, 3.1000, 1.5000, 0.2000],
        [5.0000, 3.6000, 1.4000, 0.2000]], dtype=torch.float64)

Labels (y):
tensor([0, 0, 0, 0, 0])
Which correspond to flower types: ['setosa', 'setosa', 'setosa', 'setosa', 'setosa']


# _________________________________________________________________

In [3]:
# Can you find a pytorch function that does one hot encoding?

# `torch.nn.functional.one_hot`

In [6]:
y_tensor.shape
y_tensor_one_hot = torch.nn.functional.one_hot(y_tensor)
y_tensor_one_hot.shape

torch.Size([150, 3])

In [14]:
## Pytorch and numpy mechs underlying.......

# try torch.from_numpy instead of torch.tensor

iris = load_iris()
X, y = iris.data, iris.target

X,y = np.array(X), np.array(y)

print(X.shape, y.shape)

X_tensor = torch.from_numpy(X).float()
y_tensor = torch.from_numpy(y).long()

print(X[0,0],X_tensor[0,0])


X[0,0] = 100

print(X[0,0],X_tensor[0,0])


(150, 4) (150,)
5.1 tensor(5.1000)
100.0 tensor(5.1000)


In [16]:

###

# Reproducing the exact example from above but from sklearn.dataset.load_wine

###

import torch
import sklearn
from sklearn.datasets import load_wine
import numpy as np


print(f"Pytorch version : { torch.__version__ }")
print(f"sklearn - version : {sklearn.__version__}")



################################################
# Load the dataset

wine = load_wine()
X = wine.data
y = wine.target

print(f"X.datatype : {X.dtype}, y.datatype : {y.dtype}")


############################################
# Convertour dataset to pytorch tensors




# X is our feature matrix
# Neural networks typically expect input data to be float

X_tensor = torch.tensor(X, dtype=torch.float64)

# y is our label vector
# Labels for classification are often long integers
# Hence, the dtype 'long'
y_tensor = torch.tensor(y, dtype=torch.long)


# Let's see what we've created.
print("--- Tensor Properties ---")
print(f"Shape of features tensor: {X_tensor.shape}")
print(f"Shape of labels tensor: {y_tensor.shape}\n")

print(f"Data type of features tensor: {X_tensor.dtype}")
print(f"Data type of labels tensor: {y_tensor.dtype}\n")

# .device tells us if the tensor is on the CPU or a GPU. For now, it's CPU.
print(f"Device tensor is stored on: {X_tensor.device}\n")





# --- 4. See the Data ---
# Let's look at the first 5 rows of our data, now as a PyTorch Tensor.
print("--- First 5 Samples ---")
print("Features (X):")
print(X_tensor[:5])
print("\nLabels (y):")
print(y_tensor[:5])
print(f"Which correspond to flower types: {[iris.target_names[i] for i in y_tensor[:5]]}")


Pytorch version : 2.5.1
sklearn - version : 1.6.1
X.datatype : float64, y.datatype : int32
--- Tensor Properties ---
Shape of features tensor: torch.Size([178, 13])
Shape of labels tensor: torch.Size([178])

Data type of features tensor: torch.float64
Data type of labels tensor: torch.int64

Device tensor is stored on: cpu

--- First 5 Samples ---
Features (X):
tensor([[1.4230e+01, 1.7100e+00, 2.4300e+00, 1.5600e+01, 1.2700e+02, 2.8000e+00,
         3.0600e+00, 2.8000e-01, 2.2900e+00, 5.6400e+00, 1.0400e+00, 3.9200e+00,
         1.0650e+03],
        [1.3200e+01, 1.7800e+00, 2.1400e+00, 1.1200e+01, 1.0000e+02, 2.6500e+00,
         2.7600e+00, 2.6000e-01, 1.2800e+00, 4.3800e+00, 1.0500e+00, 3.4000e+00,
         1.0500e+03],
        [1.3160e+01, 2.3600e+00, 2.6700e+00, 1.8600e+01, 1.0100e+02, 2.8000e+00,
         3.2400e+00, 3.0000e-01, 2.8100e+00, 5.6800e+00, 1.0300e+00, 3.1700e+00,
         1.1850e+03],
        [1.4370e+01, 1.9500e+00, 2.5000e+00, 1.6800e+01, 1.1300e+02, 3.8500e+00,
   

In [19]:
import torch
import sklearn
from sklearn.datasets import load_digits
import numpy as np


print(f"Pytorch version : { torch.__version__ }")
print(f"sklearn - version : {sklearn.__version__}")



################################################
# Load the dataset

digits = load_digits()
X = digits.data
y = digits.target

print(f"X.datatype : {X.dtype}, y.datatype : {y.dtype}")


############################################
# Convertour dataset to pytorch tensors




# X is our feature matrix
# Neural networks typically expect input data to be float

X_tensor = torch.tensor(X, dtype=torch.float64)

# y is our label vector
# Labels for classification are often long integers
# Hence, the dtype 'long'
y_tensor = torch.tensor(y, dtype=torch.long)


# Let's see what we've created.
print("--- Tensor Properties ---")
print(f"Shape of features tensor: {X_tensor.shape}")
print(f"Shape of labels tensor: {y_tensor.shape}\n")

print(f"Data type of features tensor: {X_tensor.dtype}")
print(f"Data type of labels tensor: {y_tensor.dtype}\n")

# .device tells us if the tensor is on the CPU or a GPU. For now, it's CPU.
print(f"Device tensor is stored on: {X_tensor.device}\n")





# --- 4. See the Data ---
# Let's look at the first 5 rows of our data, now as a PyTorch Tensor.
print("--- First 5 Samples ---")
print("Features (X):")
print(X_tensor[:5])
print("\nLabels (y):")
print(y_tensor[:5])


Pytorch version : 2.5.1
sklearn - version : 1.6.1
X.datatype : float64, y.datatype : int32
--- Tensor Properties ---
Shape of features tensor: torch.Size([1797, 64])
Shape of labels tensor: torch.Size([1797])

Data type of features tensor: torch.float64
Data type of labels tensor: torch.int64

Device tensor is stored on: cpu

--- First 5 Samples ---
Features (X):
tensor([[ 0.,  0.,  5., 13.,  9.,  1.,  0.,  0.,  0.,  0., 13., 15., 10., 15.,
          5.,  0.,  0.,  3., 15.,  2.,  0., 11.,  8.,  0.,  0.,  4., 12.,  0.,
          0.,  8.,  8.,  0.,  0.,  5.,  8.,  0.,  0.,  9.,  8.,  0.,  0.,  4.,
         11.,  0.,  1., 12.,  7.,  0.,  0.,  2., 14.,  5., 10., 12.,  0.,  0.,
          0.,  0.,  6., 13., 10.,  0.,  0.,  0.],
        [ 0.,  0.,  0., 12., 13.,  5.,  0.,  0.,  0.,  0.,  0., 11., 16.,  9.,
          0.,  0.,  0.,  0.,  3., 15., 16.,  6.,  0.,  0.,  0.,  7., 15., 16.,
         16.,  2.,  0.,  0.,  0.,  0.,  1., 16., 16.,  3.,  0.,  0.,  0.,  0.,
          1., 16., 16.,  6.,  0